title: My Portfolio Site
profile_img: /assets/img/logo.png
icon_img: /assets/img/logo.png

name: "Lance Nelson"
job: "Backend Software Engineer"

phone_number: 732-232-6935
address: Point Pleasant, New Jersey
email: LanceN04@gmail.com
linkedin_username: www.linkedin.com/in/lance-nelson
github_username: https://github.com/LancePants97
instagram_username: lance_toyf
twitter_username: n/a
facebook_username: https://www.facebook.com/lance.nelson.370177

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl:

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag